<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jn_lighterbox"
 *
 * Auto generated by Extension Builder 2017-09-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => '[joppnet] Lightbox',
	'description' => 'A very lightweight Lightbox extension for click-enlarging content element images using lightbox2.',
	'category' => 'plugin',
	'author' => 'Stefan Riedel, Oliver Schlöbe',
	'author_email' => 'stefan.riedel@joppnet.de, oli@joppnet.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '1.0.0',
	'constraints' => 
	array (
	  'depends' => 
	  array (
	    'typo3' => '8.0.0-8.7.99',
	  ),
	  'conflicts' => 
	  array (
	  ),
	  'suggests' => 
	  array (
	  ),
	),
);

?>