<?php
/***************************************************************
 * Extension Manager/Repository config file for ext: "jn_lightbox"
 *
 * Auto generated by Extension Builder 2017-09-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[joppnet] Lightbox',
    'description' => 'A very lightweight Lightbox extension for click-enlarging content element images using lightbox2.',
    'category' => 'plugin',
    'author' => 'Stefan Riedel, Oliver Schloebe',
    'author_email' => 'stefan.riedel@joppnet.de, oli@joppnet.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
